name: refugium
description: A safe space for people living with dissociative identity disorder.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #Paths
  path: ^1.9.0
  path_provider: ^2.1.4
  
  # State Management
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  # Datenbank
  drift: ^2.21.0
  drift_flutter: ^0.2.4
  sqlcipher_flutter_libs: ^0.5.0
  sqlite3: ^2.9.4

  # Verschlüsselung & Sicherheit
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0

  # i18n
  slang: ^4.4.0
  slang_flutter: ^4.4.0

  # Datenklassen
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # PDF Export
  pdf: ^3.11.1
  printing: ^5.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Codegen
  build_runner: ^2.15.0
  drift_dev: ^2.21.0
  riverpod_generator: ^4.0.3
  freezed: ^3.2.5
  json_serializable: ^6.8.0
  slang_build_runner: ^4.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/